require './html_builder'
class Navlinks

NAVLINKS = [
	{campus:"university", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"university", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"university", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"university", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"university", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"university", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"university", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"university", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"university", section:"/aboutjwu/affiliations/", name:"Campus Specific", url:"/aboutjwu/affiliations/campus/"},
	{campus:"university", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"university", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"university", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"university", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Arts & Sciences", url:"/aboutjwu/academicdirectories/artsandsciences/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Business", url:"/aboutjwu/academicdirectories/business/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Culinary Arts", url:"/aboutjwu/academicdirectories/culinaryarts/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Graduate School", url:"/aboutjwu/academicdirectories/graduate/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Hospitality", url:"/aboutjwu/academicdirectories/hospitality/"},
	{campus:"university", section:"/aboutjwu/academicdirectories/", name:"Technology", url:"/aboutjwu/academicdirectories/technology/"},
	{campus:"university", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"university", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"university", section:"/programsofstudy/", name:"Arts & Sciences", url:"/programsofstudy/artsandsciences/"},
	{campus:"university", section:"/programsofstudy/", name:"Business", url:"/programsofstudy/business/"},
	{campus:"university", section:"/programsofstudy/", name:"Culinary", url:"/programsofstudy/culinary/"},
	{campus:"university", section:"/programsofstudy/", name:"Hospitality", url:"/programsofstudy/hospitality/"},
	{campus:"university", section:"/programsofstudy/", name:"Technology", url:"/programsofstudy/technology/"},
	{campus:"university", section:"/programsofstudy/", name:"Graduate", url:"/programsofstudy/grad/"},
	{campus:"university", section:"/programsofstudy/", name:"Adult & CE", url:"/programsofstudy/adultandce/"},
	{campus:"university", section:"/programsofstudy/", name:"Online Learning", url:"/programsofstudy/online/"},
	{campus:"university", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"university", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"university", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"university", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"university", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"university", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"university", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"university", section:"/academicinformation/academicpolicies/", name:"Attendance & Tardiness", url:"/academicinformation/academicpolicies/attendanceandtardiness/"},
	{campus:"university", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"university", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"university", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"university", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"university", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"university", section:"/academicinformation/", name:"Service Learning", url:"/academicinformation/servicelearning/"},
	{campus:"university", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"university", section:"/academicinformation/", name:"Study Abroad", url:"/academicinformation/studyabroad/"},
	{campus:"university", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"university", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"university", section:"/academicinformation/honors/", name:"Latin Honors", url:"/academicinformation/honors/latin/"},
	{campus:"university", section:"/academicinformation/honors/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"university", section:"/academicinformation/honors/", name:"Academic Societies", url:"/academicinformation/honors/academicsocieties/"},
	{campus:"university", section:"/academicinformation/honors/", name:"Awards", url:"/academicinformation/honors/awards/"},
	{campus:"university", section:"/academicinformation/honors/", name:"SHARP Program", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"university", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"university", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"university", section:"/admissions/applying/", name:"High School Verification", url:"/admissions/applying/highschoolverification/"},
	{campus:"university", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"university", section:"/admissions/applying/", name:"Program Requirements", url:"/admissions/applying/graderequirements/"},
	{campus:"university", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"university", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"university", section:"/admissions/applying/", name:"Advanced Placement", url:"/admissions/applying/advancedplacement/"},
	{campus:"university", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"university", section:"/admissions/applying/", name:"Home-Schooled Students", url:"/admissions/applying/homeschooledstudents/"},
	{campus:"university", section:"/admissions/applying/", name:"Early/Dual Enrollment", url:"/admissions/applying/earlydualenrollment/"},
	{campus:"university", section:"/admissions/applying/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"university", section:"/admissions/applying/", name:"Undeclared", url:"/admissions/applying/undeclared/"},
	{campus:"university", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"university", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"university", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"university", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"university", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"university", section:"/admissions/international/", name:"Transfer Credit", url:"/admissions/international/transfercredit/"},
	{campus:"university", section:"/admissions/international/", name:"Articulation Agreements", url:"/admissions/international/articulationagreements/"},
	{campus:"university", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"university", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"university", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"university", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"university", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"university", section:"/admissions/", name:"Accelerated Programs", url:"/admissions/acceleratedprograms/"},
	{campus:"university", section:"/admissions/acceleratedprograms/", name:"Culinary Advanced Standing", url:"/admissions/acceleratedprograms/culinaryadvancedstanding/"},
	{campus:"university", section:"/admissions/acceleratedprograms/", name:"FAST & College Credit", url:"/admissions/acceleratedprograms/fastandcollegecredit/"},
	{campus:"university", section:"/admissions/acceleratedprograms/", name:"International Baccalaureate", url:"/admissions/acceleratedprograms/internationalbaccalaureate/"},
	{campus:"university", section:"/admissions/acceleratedprograms/", name:"SHARP", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"university", section:"/admissions/acceleratedprograms/", name:"4+1 Degrees", url:"/admissions/acceleratedprograms/4+1degrees/"},
	{campus:"university", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"university", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"university", section:"/financingyourdegree/tuitionfees/", name:"Extension Students", url:"/financingyourdegree/tuitionfees/extensionstudents/"},
	{campus:"university", section:"/financingyourdegree/tuitionfees/", name:"Early Enrollment", url:"/financingyourdegree/tuitionfees/earlyenrollment/"},
	{campus:"university", section:"/financingyourdegree/tuitionfees/", name:"ESL Students", url:"/financingyourdegree/tuitionfees/eslstudents/"},
	{campus:"university", section:"/financingyourdegree/", name:"Other Fees", url:"/financingyourdegree/otherfees/"},
	{campus:"university", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"university", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"university", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"university", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"university", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"university", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"university", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"university", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"university", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"university", section:"/financingyourdegree/financialaid/", name:"Institutional Aid", url:"/financingyourdegree/financialaid/institutionalaid/"},
	{campus:"university", section:"/financingyourdegree/financialaid/", name:"Outside Scholarships", url:"/financingyourdegree/financialaid/outsidescholarships/"},
	{campus:"university", section:"/financingyourdegree/financialaid/", name:"Work Programs", url:"/financingyourdegree/financialaid/workprograms/"},
	{campus:"university", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"university", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"university", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"university", section:"/studentservices/", name:"Counseling Services", url:"/studentservices/counselingservices/"},
	{campus:"university", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"university", section:"/studentservices/", name:"International Services", url:"/studentservices/internationalservices/"},
	{campus:"university", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"university", section:"/studentservices/", name:"Residential Life", url:"/studentservices/residentiallife/"},
	{campus:"university", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"university", section:"/studentservices/", name:"Student Activities", url:"/studentactivities/"},
	{campus:"university", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"denver-ce", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"denver-ce", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"denver-ce", section:"/aboutjwu/affiliations/", name:"Campus Specific", url:"/aboutjwu/affiliations/campus/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"denver-ce", section:"/aboutjwu/academicdirectories/", name:"Arts & Sciences", url:"/aboutjwu/academicdirectories/artsandsciences/"},
	{campus:"denver-ce", section:"/aboutjwu/academicdirectories/", name:"Business", url:"/aboutjwu/academicdirectories/business/"},
	{campus:"denver-ce", section:"/aboutjwu/academicdirectories/", name:"Culinary Arts", url:"/aboutjwu/academicdirectories/culinaryarts/"},
	{campus:"denver-ce", section:"/aboutjwu/academicdirectories/", name:"Hospitality", url:"/aboutjwu/academicdirectories/hospitality/"},
	{campus:"denver-ce", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"denver-ce", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"denver-ce", section:"/programsofstudy/", name:"Adult & CE", url:"/programsofstudy/adultandce/"},
	{campus:"denver-ce", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"denver-ce", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"denver-ce", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"denver-ce", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"denver-ce", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"denver-ce", section:"/academicinformation/academicpolicies/", name:"Attendance & Tardiness", url:"/academicinformation/academicpolicies/attendanceandtardiness/"},
	{campus:"denver-ce", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"denver-ce", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"denver-ce", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"denver-ce", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"denver-ce", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"denver-ce", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"High School Verification", url:"/admissions/applying/highschoolverification/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Advanced Placement", url:"/admissions/applying/advancedplacement/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"denver-ce", section:"/admissions/applying/", name:"Home-Schooled Students", url:"/admissions/applying/homeschooledstudents/"},
	{campus:"denver-ce", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"denver-ce", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"denver-ce", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"denver-ce", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"denver-ce", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"denver-ce", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"denver-ce", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"denver-ce", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"denver-ce", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"denver-ce", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"denver-ce", section:"/admissions/", name:"Advanced Culinary", url:"/admissions/advancedculinary/"},
	{campus:"denver-ce", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Other Fees", url:"/financingyourdegree/otherfees/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"denver-ce", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"denver-ce", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"denver-ce", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"denver-ce", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"denver-ce", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"denver-ce", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"denver-ce", section:"/studentservices/", name:"Student Activities", url:"/studentactivities/"},
	{campus:"grad", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"grad", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"grad", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"grad", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"grad", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"grad", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"grad", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"grad", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"grad", section:"/aboutjwu/affiliations/", name:"Graduate School", url:"/aboutjwu/affiliations/campus/"},
	{campus:"grad", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"grad", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"grad", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"grad", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"grad", section:"/aboutjwu/academicdirectories/", name:"Graduate School", url:"/aboutjwu/academicdirectories/graduate/"},
	{campus:"grad", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"grad", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"grad", section:"/programsofstudy/", name:"Graduate", url:"/programsofstudy/grad/"},
	{campus:"grad", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"grad", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"grad", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"grad", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"grad", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"grad", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Attendance", url:"/academicinformation/academicpolicies/attendance/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Course Registration", url:"/academicinformation/academicpolicies/courseregistration/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Full-time Status", url:"/academicinformation/academicpolicies/fulltimestatus/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"MBA Prereqs", url:"/academicinformation/academicpolicies/mbaprerequisites/"},
	{campus:"grad", section:"/academicinformation/academicpolicies/", name:"Reinstatement", url:"/academicinformation/academicpolicies/reinstatement/"},
	{campus:"grad", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"grad", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"grad", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"grad", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"grad", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"grad", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"grad", section:"/admissions/applying/", name:"MBA/MS", url:"/admissions/applying/mbams/"},
	{campus:"grad", section:"/admissions/applying/", name:"MAT", url:"/admissions/applying/mat/"},
	{campus:"grad", section:"/admissions/applying/", name:"MEd", url:"/admissions/applying/med/"},
	{campus:"grad", section:"/admissions/applying/", name:"EdD", url:"/admissions/applying/edd/"},
	{campus:"grad", section:"/admissions/applying/", name:"Enrollment Date Change", url:"/admissions/applying/enrollmentdatechange/"},
	{campus:"grad", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"grad", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"grad", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"grad", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"grad", section:"/financingyourdegree/financialaid/", name:"Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"grad", section:"/financingyourdegree/financialaid/", name:"Institutional Aid", url:"/financingyourdegree/financialaid/institutionalaid/"},
	{campus:"grad", section:"/financingyourdegree/financialaid/", name:"Work Programs", url:"/financingyourdegree/financialaid/workprograms/"},
	{campus:"grad", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"grad", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"grad", section:"/studentservices/", name:"International Services", url:"/studentservices/internationalservices/"},
	{campus:"grad", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"grad", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"grad", section:"/studentservices/", name:"Prof. Comm. Center", url:"/studentservices/profcommcenter/"},
	{campus:"grad", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"grad", section:"/studentservices/", name:"Students w/Disabilities", url:"/studentservices/studentswdisabilities/"},
	{campus:"online", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"online", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"online", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"online", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"online", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"online", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"online", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/general/"},
	{campus:"online", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"online", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"online", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"online", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"online", section:"/programsofstudy/", name:"Online Learning", url:"/programsofstudy/online/"},
	{campus:"online", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"online", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"online", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"online", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Attendance", url:"/academicinformation/academicpolicies/attendance/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Plagiarism/turnitin", url:"/academicinformation/academicpolicies/plagiarismturnitin/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"online", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"online", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"online", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"online", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"online", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"online", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"online", section:"/academicinformation/honors/", name:"Academic Societies", url:"/academicinformation/honors/academicsocieties/"},
	{campus:"online", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"online", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"online", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"online", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"online", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"online", section:"/admissions/applying/", name:"JWU Alumni", url:"/admissions/applying/jwualumni/"},
	{campus:"online", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"online", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"online", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"online", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"online", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"online", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"online", section:"/admissions/international/", name:"Transfer Credit", url:"/admissions/international/transfercredit/"},
	{campus:"online", section:"/admissions/international/", name:"Articulation Agreements", url:"/admissions/international/articulationagreements/"},
	{campus:"online", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"online", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"online", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"online", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"online", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"online", section:"/admissions/", name:"International Baccalaureate", url:"/admissions/acceleratedprograms/internationalbaccalaureate/"},
	{campus:"online", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"online", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"online", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"online", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"online", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"online", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"online", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"online", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"online", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"online", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"online", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"online", section:"/financingyourdegree/financialaid/", name:"Institutional Aid", url:"/financingyourdegree/financialaid/institutionalaid/"},
	{campus:"online", section:"/financingyourdegree/financialaid/", name:"Outside Scholarships", url:"/financingyourdegree/financialaid/outsidescholarships/"},
	{campus:"online", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"online", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"online", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"online", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"online", section:"/studentservices/", name:"Residency Housing", url:"/studentservices/residencyhousng/"},
	{campus:"online", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"providence-ce", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"providence-ce", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"providence-ce", section:"/aboutjwu/affiliations/", name:"Campus Specific", url:"/aboutjwu/affiliations/campus/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Arts & Sciences", url:"/aboutjwu/academicdirectories/artsandsciences/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Business", url:"/aboutjwu/academicdirectories/business/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Culinary Arts", url:"/aboutjwu/academicdirectories/culinaryarts/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Graduate School", url:"/aboutjwu/academicdirectories/graduate/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Hospitality", url:"/aboutjwu/academicdirectories/hospitality/"},
	{campus:"providence-ce", section:"/aboutjwu/academicdirectories/", name:"Technology", url:"/aboutjwu/academicdirectories/technology/"},
	{campus:"providence-ce", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"providence-ce", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"providence-ce", section:"/programsofstudy/", name:"Adult & CE", url:"/programsofstudy/adultandce/"},
	{campus:"providence-ce", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"providence-ce", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"providence-ce", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"providence-ce", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"providence-ce", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"providence-ce", section:"/academicinformation/academicpolicies/", name:"Attendance & Tardiness", url:"/academicinformation/academicpolicies/attendanceandtardiness/"},
	{campus:"providence-ce", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"providence-ce", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"providence-ce", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Study Abroad", url:"/academicinformation/studyabroad/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"providence-ce", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"providence-ce", section:"/academicinformation/honors/", name:"Academic Societies ", url:"/academicinformation/honors/academicsocieties/"},
	{campus:"providence-ce", section:"/academicinformation/honors/", name:"Awards ", url:"/academicinformation/honors/awards/"},
	{campus:"providence-ce", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"providence-ce", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"High School Verification", url:"/admissions/applying/highschoolverification/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Advanced Placement", url:"/admissions/applying/advancedplacement/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"providence-ce", section:"/admissions/applying/", name:"Home-Schooled Students", url:"/admissions/applying/homeschooledstudents/"},
	{campus:"providence-ce", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"providence-ce", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"providence-ce", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"providence-ce", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"providence-ce", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"providence-ce", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"providence-ce", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"providence-ce", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"providence-ce", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"providence-ce", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"providence-ce", section:"/admissions/", name:"Advanced Culinary", url:"/admissions/advancedculinary/"},
	{campus:"providence-ce", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Other Fees", url:"/financingyourdegree/otherfees/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"providence-ce", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"providence-ce", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"providence-ce", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"providence-ce", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"providence-ce", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"providence-ce", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"providence-ce", section:"/studentservices/", name:"International Services", url:"/studentservices/internationalservices/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Parking", url:"/studentservices/parking/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"providence-ce", section:"/studentservices/", name:"Student Activities", url:"/studentactivities/"},
	{campus:"providence", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"providence", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"providence", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"providence", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"providence", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"providence", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"providence", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"providence", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"providence", section:"/aboutjwu/affiliations/", name:"Campus Specific", url:"/aboutjwu/affiliations/campus/"},
	{campus:"providence", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"providence", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"providence", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"providence", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Arts & Sciences", url:"/aboutjwu/academicdirectories/artsandsciences/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Business", url:"/aboutjwu/academicdirectories/business/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Culinary Arts", url:"/aboutjwu/academicdirectories/culinaryarts/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Graduate School", url:"/aboutjwu/academicdirectories/graduate/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Hospitality", url:"/aboutjwu/academicdirectories/hospitality/"},
	{campus:"providence", section:"/aboutjwu/academicdirectories/", name:"Technology", url:"/aboutjwu/academicdirectories/technology/"},
	{campus:"providence", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"providence", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"providence", section:"/programsofstudy/", name:"Arts & Sciences", url:"/programsofstudy/artsandsciences/"},
	{campus:"providence", section:"/programsofstudy/", name:"Business", url:"/programsofstudy/business/"},
	{campus:"providence", section:"/programsofstudy/", name:"Culinary", url:"/programsofstudy/culinary/"},
	{campus:"providence", section:"/programsofstudy/", name:"Hospitality", url:"/programsofstudy/hospitality/"},
	{campus:"providence", section:"/programsofstudy/", name:"Technology", url:"/programsofstudy/technology/"},
	{campus:"providence", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"providence", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"providence", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"providence", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"providence", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"providence", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"providence", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"providence", section:"/academicinformation/academicpolicies/", name:"Attendance & Tardiness", url:"/academicinformation/academicpolicies/attendanceandtardiness/"},
	{campus:"providence", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"providence", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"providence", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"providence", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"providence", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"providence", section:"/academicinformation/", name:"Service Learning", url:"/academicinformation/servicelearning/"},
	{campus:"providence", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"providence", section:"/academicinformation/", name:"Study Abroad", url:"/academicinformation/studyabroad/"},
	{campus:"providence", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"providence", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"providence", section:"/academicinformation/honors/", name:"Latin Honors", url:"/academicinformation/honors/latin/"},
	{campus:"providence", section:"/academicinformation/honors/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"providence", section:"/academicinformation/honors/", name:"Academic Societies", url:"/academicinformation/honors/academicsocieties/"},
	{campus:"providence", section:"/academicinformation/honors/", name:"Awards", url:"/academicinformation/honors/awards/"},
	{campus:"providence", section:"/academicinformation/honors/", name:"SHARP Program", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"providence", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"providence", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"providence", section:"/admissions/applying/", name:"High School Verification", url:"/admissions/applying/highschoolverification/"},
	{campus:"providence", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"providence", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"providence", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"providence", section:"/admissions/applying/", name:"Advanced Placement", url:"/admissions/applying/advancedplacement/"},
	{campus:"providence", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"providence", section:"/admissions/applying/", name:"Home-Schooled Students", url:"/admissions/applying/homeschooledstudents/"},
	{campus:"providence", section:"/admissions/applying/", name:"Early/Dual Enrollment", url:"/admissions/applying/earlydualenrollment/"},
	{campus:"providence", section:"/admissions/applying/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"providence", section:"/admissions/applying/", name:"Undeclared", url:"/admissions/applying/undeclared/"},
	{campus:"providence", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"providence", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"providence", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"providence", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"providence", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"providence", section:"/admissions/international/", name:"Transfer Credit", url:"/admissions/international/transfercredit/"},
	{campus:"providence", section:"/admissions/international/", name:"Articulation Agreements", url:"/admissions/international/articulationagreements/"},
	{campus:"providence", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"providence", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"providence", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"providence", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"providence", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"providence", section:"/admissions/", name:"Accelerated Programs", url:"/admissions/acceleratedprograms/"},
	{campus:"providence", section:"/admissions/acceleratedprograms/", name:"Culinary Advanced Standing", url:"/admissions/acceleratedprograms/culinaryadvancedstanding/"},
	{campus:"providence", section:"/admissions/acceleratedprograms/", name:"FAST & College Credit", url:"/admissions/acceleratedprograms/fastandcollegecredit/"},
	{campus:"providence", section:"/admissions/acceleratedprograms/", name:"International Baccalaureate", url:"/admissions/acceleratedprograms/internationalbaccalaureate/"},
	{campus:"providence", section:"/admissions/acceleratedprograms/", name:"SHARP", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"providence", section:"/admissions/acceleratedprograms/", name:"4+1 Degrees", url:"/admissions/acceleratedprograms/4+1degrees/"},
	{campus:"providence", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"providence", section:"/financingyourdegree/tuitionfees/", name:"Extension Students", url:"/financingyourdegree/tuitionfees/extensionstudents/"},
	{campus:"providence", section:"/financingyourdegree/tuitionfees/", name:"Early Enrollment", url:"/financingyourdegree/tuitionfees/earlyenrollment/"},
	{campus:"providence", section:"/financingyourdegree/tuitionfees/", name:"ESL Students", url:"/financingyourdegree/tuitionfees/eslstudents/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Other Fees", url:"/financingyourdegree/otherfees/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"providence", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"providence", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"providence", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"providence", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"providence", section:"/financingyourdegree/financialaid/", name:"Institutional Aid", url:"/financingyourdegree/financialaid/institutionalaid/"},
	{campus:"providence", section:"/financingyourdegree/financialaid/", name:"Outside Scholarships", url:"/financingyourdegree/financialaid/outsidescholarships/"},
	{campus:"providence", section:"/financingyourdegree/financialaid/", name:"Work Programs", url:"/financingyourdegree/financialaid/workprograms/"},
	{campus:"providence", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"providence", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"providence", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"providence", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"providence", section:"/studentservices/", name:"International Services", url:"/studentservices/internationalservices/"},
	{campus:"providence", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"providence", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"providence", section:"/studentservices/", name:"Residential Life", url:"/studentservices/residentiallife/"},
	{campus:"providence", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"providence", section:"/studentservices/", name:"Student Activities", url:"/studentactivities/"},
	{campus:"other", section:"/", name:"About JWU", url:"/aboutjwu/"},
	{campus:"other", section:"/aboutjwu/", name:"Letter from President", url:"/aboutjwu/letterfromthepresident/"},
	{campus:"other", section:"/aboutjwu/", name:"History of JWU", url:"/aboutjwu/historyofjwu/"},
	{campus:"other", section:"/aboutjwu/", name:"Mission & Principles", url:"/aboutjwu/missionandpurposes/"},
	{campus:"other", section:"/aboutjwu/", name:"Campus Facilities", url:"/aboutjwu/campuses/"},
	{campus:"other", section:"/aboutjwu/", name:"Accreditations", url:"/aboutjwu/accreditations/"},
	{campus:"other", section:"/aboutjwu/", name:"Affiliations", url:"/aboutjwu/affiliations/"},
	{campus:"other", section:"/aboutjwu/affiliations/", name:"General University", url:"/aboutjwu/affiliations/general/"},
	{campus:"other", section:"/aboutjwu/affiliations/", name:"Campus Specific", url:"/aboutjwu/affiliations/campus/"},
	{campus:"other", section:"/aboutjwu/", name:"Nondiscrimination Notice", url:"/aboutjwu/nondiscriminationnotice/"},
	{campus:"other", section:"/aboutjwu/", name:"Corporation & Trustees", url:"/aboutjwu/corporationandtrustees/"},
	{campus:"other", section:"/aboutjwu/", name:"University Leadership", url:"/aboutjwu/universityleadership/"},
	{campus:"other", section:"/aboutjwu/", name:"Academic Directories", url:"/aboutjwu/academicdirectories/"},
	{campus:"other", section:"/aboutjwu/academicdirectories/", name:"Arts & Sciences", url:"/aboutjwu/academicdirectories/artsandsciences/"},
	{campus:"other", section:"/aboutjwu/academicdirectories/", name:"Business", url:"/aboutjwu/academicdirectories/business/"},
	{campus:"other", section:"/aboutjwu/academicdirectories/", name:"Culinary Arts", url:"/aboutjwu/academicdirectories/culinaryarts/"},
	{campus:"other", section:"/aboutjwu/academicdirectories/", name:"Hospitality", url:"/aboutjwu/academicdirectories/hospitality/"},
	{campus:"other", section:"/aboutjwu/", name:"Department Directories", url:"/aboutjwu/departmentdirectories/"},
	{campus:"other", section:"/", name:"Programs of Study", url:"/programsofstudy/"},
	{campus:"other", section:"/programsofstudy/", name:"Arts & Sciences", url:"/programsofstudy/artsandsciences/"},
	{campus:"other", section:"/programsofstudy/", name:"Business", url:"/programsofstudy/business/"},
	{campus:"other", section:"/programsofstudy/", name:"Culinary", url:"/programsofstudy/culinary/"},
	{campus:"other", section:"/programsofstudy/", name:"Hospitality", url:"/programsofstudy/hospitality/"},
	{campus:"other", section:"/programsofstudy/", name:"Full Course Listing", url:"/programsofstudy/fullcourselisting/"},
	{campus:"other", section:"/", name:"Academic Information", url:"/academicinformation/"},
	{campus:"other", section:"/academicinformation/", name:"Academic Calendars", url:"/academicinformation/academiccalendars/"},
	{campus:"other", section:"/academicinformation/academiccalendars/", name:"Class Schedules", url:"/academicinformation/academiccalendars/classschedules/"},
	{campus:"other", section:"/academicinformation/academiccalendars/", name:"Summer Sessions", url:"/academicinformation/academiccalendars/summersessions/"},
	{campus:"other", section:"/academicinformation/", name:"Academic Policies", url:"/academicinformation/academicpolicies/"},
	{campus:"other", section:"/academicinformation/academicpolicies/", name:"Academic Standing", url:"/academicinformation/academicpolicies/academicstandards/"},
	{campus:"other", section:"/academicinformation/academicpolicies/", name:"Attendance & Tardiness", url:"/academicinformation/academicpolicies/attendanceandtardiness/"},
	{campus:"other", section:"/academicinformation/academicpolicies/", name:"Credits & Grades", url:"/academicinformation/academicpolicies/creditsandgrades/"},
	{campus:"other", section:"/academicinformation/academicpolicies/", name:"Repeat of Courses", url:"/academicinformation/academicpolicies/repeatofcourses/"},
	{campus:"other", section:"/academicinformation/academicpolicies/", name:"Transfer & Career Prerequisites", url:"/academicinformation/academicpolicies/transferandcareerprerequisites/"},
	{campus:"other", section:"/academicinformation/", name:"Transcripts", url:"/academicinformation/transcripts/"},
	{campus:"other", section:"/academicinformation/", name:"Requirements", url:"/academicinformation/requirements/"},
	{campus:"other", section:"/academicinformation/", name:"Experiential Education", url:"/academicinformation/experientialeducation/"},
	{campus:"other", section:"/academicinformation/", name:"Study Abroad", url:"/academicinformation/studyabroad/"},
	{campus:"other", section:"/academicinformation/", name:"Academic Functions", url:"/academicinformation/academicfunctions/"},
	{campus:"other", section:"/academicinformation/", name:"Honors", url:"/academicinformation/honors/"},
	{campus:"other", section:"/academicinformation/honors/", name:"Latin Honors", url:"/academicinformation/honors/latin/"},
	{campus:"other", section:"/academicinformation/honors/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"other", section:"/academicinformation/honors/", name:"Academic Societies", url:"/academicinformation/honors/academicsocieties/"},
	{campus:"other", section:"/academicinformation/honors/", name:"Awards", url:"/academicinformation/honors/awards/"},
	{campus:"other", section:"/academicinformation/honors/", name:"SHARP Program", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"other", section:"/", name:"Admissions", url:"/admissions/"},
	{campus:"other", section:"/admissions/", name:"Applying", url:"/admissions/applying/"},
	{campus:"other", section:"/admissions/applying/", name:"High School Verification", url:"/admissions/applying/highschoolverification/"},
	{campus:"other", section:"/admissions/applying/", name:"Admissions Requirements", url:"/admissions/applying/admissionsrequirements/"},
	{campus:"other", section:"/admissions/applying/", name:"Admissions Decision", url:"/admissions/applying/admissionsdecision/"},
	{campus:"other", section:"/admissions/applying/", name:"Deferred Enrollment", url:"/admissions/applying/deferredenrollment/"},
	{campus:"other", section:"/admissions/applying/", name:"Advanced Placement", url:"/admissions/applying/advancedplacement/"},
	{campus:"other", section:"/admissions/applying/", name:"Transfer Students", url:"/admissions/applying/transferstudents/"},
	{campus:"other", section:"/admissions/applying/", name:"Home-Schooled Students", url:"/admissions/applying/homeschooledstudents/"},
	{campus:"other", section:"/admissions/applying/", name:"Early/Dual Enrollment", url:"/admissions/applying/earlydualenrollment/"},
	{campus:"other", section:"/admissions/applying/", name:"Honors Program", url:"/academicinformation/honors/program/"},
	{campus:"other", section:"/admissions/", name:"Technical Standards", url:"/admissions/technicalstandards/"},
	{campus:"other", section:"/admissions/", name:"Military", url:"/admissions/military/"},
	{campus:"other", section:"/admissions/", name:"International", url:"/admissions/international/"},
	{campus:"other", section:"/admissions/international/", name:"English Language Proficiency", url:"/admissions/international/englishlanguageproficiency/"},
	{campus:"other", section:"/admissions/international/", name:"English Proficiency Requirements", url:"/admissions/international/toeflrequirements/"},
	{campus:"other", section:"/admissions/international/", name:"Transfer Credit", url:"/admissions/international/transfercredit/"},
	{campus:"other", section:"/admissions/international/", name:"Articulation Agreements", url:"/admissions/international/articulationagreements/"},
	{campus:"other", section:"/admissions/", name:"Placement Testing", url:"/admissions/placementtesting/"},
	{campus:"other", section:"/admissions/", name:"Learning Assessment", url:"/admissions/learningassessment/"},
	{campus:"other", section:"/admissions/learningassessment/", name:"Portfolio Assessment", url:"/admissions/learningassessment/portfolio/"},
	{campus:"other", section:"/admissions/learningassessment/", name:"CLEP Examination", url:"/admissions/learningassessment/clepexamination/"},
	{campus:"other", section:"/admissions/learningassessment/", name:"Departmental Challenge Examination", url:"/admissions/learningassessment/departmentalchallenge/"},
	{campus:"other", section:"/admissions/", name:"Accelerated Programs", url:"/admissions/acceleratedprograms/"},
	{campus:"other", section:"/admissions/acceleratedprograms/", name:"Culinary Advanced Standing", url:"/admissions/acceleratedprograms/culinaryadvancedstanding/"},
	{campus:"other", section:"/admissions/acceleratedprograms/", name:"FAST & College Credit", url:"/admissions/acceleratedprograms/fastandcollegecredit/"},
	{campus:"other", section:"/admissions/acceleratedprograms/", name:"International Baccalaureate", url:"/admissions/acceleratedprograms/internationalbaccalaureate/"},
	{campus:"other", section:"/admissions/acceleratedprograms/", name:"SHARP", url:"/admissions/acceleratedprograms/sharp/"},
	{campus:"other", section:"/admissions/acceleratedprograms/", name:"4+1 Degrees", url:"/admissions/acceleratedprograms/4+1degrees/"},
	{campus:"other", section:"/", name:"Financing Your Degree", url:"/financingyourdegree/"},
	{campus:"other", section:"/financingyourdegree/", name:"Tuition & Fees", url:"/financingyourdegree/tuitionfees/"},
	{campus:"other", section:"/financingyourdegree/tuitionfees/", name:"Extension Students", url:"/financingyourdegree/tuitionfees/extensionstudents/"},
	{campus:"other", section:"/financingyourdegree/tuitionfees/", name:"Early Enrollment", url:"/financingyourdegree/tuitionfees/earlyenrollment/"},
	{campus:"other", section:"/financingyourdegree/tuitionfees/", name:"ESL Students", url:"/financingyourdegree/tuitionfees/eslstudents/"},
	{campus:"other", section:"/financingyourdegree/", name:"Other Fees", url:"/financingyourdegree/otherfees/"},
	{campus:"other", section:"/financingyourdegree/", name:"Payment Options", url:"/financingyourdegree/paymentoptions/"},
	{campus:"other", section:"/financingyourdegree/", name:"Refund Policies", url:"/financingyourdegree/refundpolicies/"},
	{campus:"other", section:"/financingyourdegree/refundpolicies/", name:"Georgia Residents", url:"/financingyourdegree/refundpolicies/georgiaresidents/"},
	{campus:"other", section:"/financingyourdegree/refundpolicies/", name:"Withdrawal Credit Policy", url:"/financingyourdegree/refundpolicies/withdrawalcreditpolicy/"},
	{campus:"other", section:"/financingyourdegree/", name:"Financial Obligations", url:"/financingyourdegree/financialobligations/"},
	{campus:"other", section:"/financingyourdegree/", name:"Financial Planning", url:"/financingyourdegree/financialplanning/"},
	{campus:"other", section:"/financingyourdegree/", name:"Financial Aid", url:"/financingyourdegree/financialaid/"},
	{campus:"other", section:"/financingyourdegree/financialaid/", name:"How to Apply", url:"/financingyourdegree/financialaid/howtoapply/"},
	{campus:"other", section:"/financingyourdegree/financialaid/", name:"Grants & Loans", url:"/financingyourdegree/financialaid/grantsandloans/"},
	{campus:"other", section:"/financingyourdegree/financialaid/", name:"Institutional Aid", url:"/financingyourdegree/financialaid/institutionalaid/"},
	{campus:"other", section:"/financingyourdegree/financialaid/", name:"Outside Scholarships", url:"/financingyourdegree/financialaid/outsidescholarships/"},
	{campus:"other", section:"/financingyourdegree/financialaid/", name:"Work Programs", url:"/financingyourdegree/financialaid/workprograms/"},
	{campus:"other", section:"/financingyourdegree/", name:"Academic Progress", url:"/financingyourdegree/academicprogress/"},
	{campus:"other", section:"/", name:"Student Services", url:"/studentservices/"},
	{campus:"other", section:"/studentservices/", name:"Academic Support", url:"/studentservices/academicsupport/"},
	{campus:"other", section:"/studentservices/", name:"Health Services", url:"/studentservices/healthservices/"},
	{campus:"other", section:"/studentservices/", name:"International Services", url:"/studentservices/internationalservices/"},
	{campus:"other", section:"/studentservices/", name:"Orientation", url:"/studentservices/orientation/"},
	{campus:"other", section:"/studentservices/", name:"Policies", url:"/studentservices/policies/"},
	{campus:"other", section:"/studentservices/", name:"Residential Life", url:"/studentservices/residentiallife/"},
	{campus:"other", section:"/studentservices/", name:"Safety & Security", url:"/studentservices/safetyandsecurity/"},
	{campus:"other", section:"/studentservices/", name:"Student Activities", url:"/studentactivities/"}
]

  def generate_html(campus, records)
    builder.build_ul do
      links = ""
      records.each do |record|
        links << builder.build_li do
          builder.build_link(record[:name], record[:url])
        end
      end
      links
    end
  end

  def find_records(campus, path)
    NAVLINKS.select { |link| link[:campus] == campus && link[:section] == path }
  end

  def breakdown_path(path)
    path_pieces = []
    index = path.index('/')
    until index.nil? do
      path_pieces << path[0, index + 1]
      index = path.index('/', index + 1)
    end
    path_pieces
  end

  private
  def builder
    @builder ||= HtmlBuilder.new
  end

end
